trigger:
  - main

resources: 
  repositories:
    - repository: templates
      type: github
      name: teenox/Infrastructure
      endpoint: teenox
      
pool:
  vmImage: 'ubuntu-latest'

jobs:
  - template: deployment/vue-static.yml@templates
    parameters:
      packageJsonFolder: '.'
      cacheKey: 'npm | "$(Agent.OS)" | ./package-lock.json'
      npmAuthenticate: false
      enableCypressCache: false   