trigger:
  - main

resources: 
  repositories:
    - repository: templates
      type: github
      name: teenox/Infrastructure
      endpoint: teenox
      
pool:
  vmImage: 'windows-latest'

jobs:
  - template: deployment/vue-static.yml@templates
    parameters:
      packageJsonFolder: './teenox/azure-static-nuxt'
      cacheKey: 'npm | "$(Agent.OS)" | ./teenox/azure-static-nuxt/package-lock.json'
      npmAuthenticate: true
      enableCypressCache: false   